### ISSUE TITLE
无法执行命令

### ISSUE THREAD

**Issue by fjaokdp** [AiCorein/Qbot-MeloBot#2]
【系统环境】
linux x86_64架构，Debian 11，Python 3.9.2

log：
[2023-03-19 08:58:53] [INFO]: Qbot-MeloBot 版本：v1.2.0, developer: 律回MelodyEcho
[2023-03-19 08:58:53] [INFO]: bot 世界观形成中...  (=´ω｀=)
[2023-03-19 08:58:53] [INFO]: bot 意识形成完毕√
[2023-03-19 08:58:53] [INFO]: bot 开始觉醒!~ >w<
[2023-03-19 08:58:53] [INFO]: 与 cq 成功建立 websocket 连接
[2023-03-19 08:59:01] [INFO]: 在 h3 调度器，命令 echo | 需要 user 权限，权限不够呢 qwq 执行成功√
[2023-03-19 09:07:07] [INFO]: 在 h1 调度器，命令 echo | 需要 user 权限，权限不够呢 qwq 执行成功√
[2023-03-19 09:07:13] [INFO]: 在 h4 调度器，命令 echo | 需要 user 权限，权限不够呢 qwq 执行成功√

**Comment by AiCorein** [comment]
v1 版估计是好多 bug 没修好（）
配置文件配置过了吗？如果是配置过之后出现的问题，
请在 utils/cmdInterface.py 106 行前临时插入这一行代码:
```python
print(event)
```
然后麻烦再发一下日志信息。

**Comment by fjaokdp** [comment]
保持默认配置只是修改了上报类型 post-format为 array

在 utils/cmdInterface.py 106 行添加后为
`                    # 若在黑名单中，什么也不做
                    if self.msg_checker.get_event_lvl(event) == self.role.BLACK:
                        return None
                    elif self.msg_checker.isMsgReport(event):
                        if not self.msg_checker.check(userLevel, event):
                            print(event)
                            return await self.sys_call('echo', event, \
                                f'需要 {self.msg_checker.auth_str_map[userLevel]} 权限，权限不够呢 qwq')
                    elif self.notice_checker.isNoticeReport(event):
                        if not self.notice_checker.check(("user_id", userLevel), event):
                            return await self.sys_call('echo', event, \
                                f'需要 {self.msg_checker.auth_str_map[userLevel]} 权限，权限不够呢 qwq')
                    else:
                        BOT_LOGGER.error(f"bot 权限校验中遇到了预期外的事件类型：{event}")
                        raise BotUnexpectedEvent("权限校验中遇到了预期外的事件类型")`

这一次的日志信息
log：
[2023-03-19 10:02:11] [INFO]: Qbot-MeloBot 版本：v1.2.0, developer: 律回MelodyEcho
[2023-03-19 10:02:11] [INFO]: bot 世界观形成中...  (=´ω｀=)
[2023-03-19 10:02:11] [INFO]: bot 意识形成完毕√
[2023-03-19 10:02:11] [INFO]: bot 开始觉醒!~ >w<
[2023-03-19 10:02:11] [INFO]: 与 cq 成功建立 websocket 连接
{'post_type': 'message', 'message_type': 'group', 'time': 1679234536, 'self_id': 1715394974, 'sub_type': 'normal', 'anonymous': None, 'user_id': QQ号, 'message_id': 1219418604, 'raw_message': 'hhh', 'sender': {'age': 0, 'area': '', 'card': 'QQ昵称', 'level': '', 'nickname': 'QQ昵称', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': QQ号}, 'font': 0, 'group_id': QQ群号, 'message': [{'type': 'text', 'data': {'text': 'hhh'}}], 'message_seq': 12718}
[2023-03-19 10:02:16] [INFO]: 在 h2 调度器，命令 echo | 需要 user 权限，权限不够呢 qwq 执行成功√
{'post_type': 'message', 'message_type': 'group', 'time': 1679234570, 'self_id': 1715394974, 'sub_type': 'normal', 'message_id': 1834484253, 'font': 0, 'message': [{'type': 'text', 'data': {'text': 'hhh'}}], 'user_id': QQ号, 'raw_message': 'hhh', 'sender': {'age': 0, 'area': '', 'card': 'QQ昵称', 'level': '', 'nickname': 'QQ昵称', 'role': 'owner', 'sex': 'unknown', 'title': '', 'user_id': QQ号}, 'anonymous': None, 'group_id': QQ群号, 'message_seq': 12720}
[2023-03-19 10:02:50] [INFO]: 在 h5 调度器，命令 echo | 需要 user 权限，权限不够呢 qwq 执行成功√


 输入：在qq输入hhh或者哈哈哈，终端输入python3 main.py。go-cqhttp 版本为v1.0.0-rc4

**Comment by AiCorein** [comment]
我这边看了一下，似乎只有在配置文件中，没把该群加入白名单列表才会出现这种情况。
关于这个配置请参考：https://aicorein.github.io/Qbot-MeloBot-docs/config/botConfig/#white-group-list

同时出现这个问题，也从侧面暴露了一个 bug：群聊不在白名单中时发送命令，也会响应提示信息。
我会立刻修复这个 bug。你可以通过以下方式快速修复这个 bug：
```python
# 在 utils/eventProcess.py 第 326 行后插入：
if self.isGroupPublicMsg(event):
    if event['group_id'] not in BOT_STORE['custom']['WHITE_GROUP_LIST']:
        return res
```

**Comment by fjaokdp** [comment]
好的。关键词在群聊已经可以正常被触发了。一开始我参考了文档，我写的是 WHITE_GROUP_LIST = ['群号码']，可能是我对配置的理解有误，这么写是无效的需要把单引号去掉，但是因为这个bug的存在我无法验证是否有把群聊添加到白名单，即便加上单引号程序也会正常运行但是不会有任何输出
